### ISSUE TITLE
[Suggestion] JEI like MachineTabs

### ISSUE THREAD

**Issue by Miradae** [GTNewHorizons/NotEnoughItems#39] opened 2021-02-04 17:37 UTC
JEI has this useful feature of offering tabs to switch between the different recipes for machines.
JEI also has a feature where you can press U on a machine and it will not only show you the recipes including the item but also offer the recipes you can do with that machine.

Esp. with Gregtech this would be an insane QoL improvement and make it much easier for new players to find their way

**Comment by Miradae** [comment] 2021-02-08 11:51
Someone already implemented something like this: https://forum.mechaenetia.com/t/mod-notenoughitems-unofficial/999
but hasn't updated since (he also recommends using this version). Maybe some of his code is reusable though. Might be worth a look

**Comment by Glease** [comment] 2021-02-08 12:35
Did you notice that one of the link in that post points back to our repo?

**Comment by Prometheus0000** [comment] 2021-02-08 12:43
Mitch hates GUI work. If you or someone else could help him with that it could get done, otherwise it may never materialize.
Also, this is a duplicate of https://github.com/GTNewHorizons/NotEnoughItems/issues/10.

**Closed by Prometheus0000** 2021-02-08 12:43 UTC
