### ISSUE TITLE
[2.1.2-GTNH] Crash when clicking on thaumcraft aspect

### ISSUE THREAD

**Issue by ORANG4** [GTNewHorizons/NotEnoughItems#123] opened 2021-05-14 18:45 UTC
Game [crashes](https://pastebin.com/JYaX4fss) when trying to view any TC aspect recipe.

**Modpack:** FTB Infinity Evolved

**Comment by tyrael93** [comment] 2021-05-16 11:57
Can reproduce in my modpack too, I thought it was a TC NEI problem and went to talk to time conqueror about it until I saw this issue.
My crashlog: https://pastebin.com/NScPtqzL

**Comment by mitchej123** [comment] 2021-05-16 17:12
What language do you guys have minecraft set to?  It's erroring out because `getRecipeName()` is returning either null, or a string < 2characters.

I'll handle it on the NEI side but looks like it might be a i18n issue

```
    @Override
    public String getRecipeName() {
        return I18n.format("tcneiadditions.aspect_combination.title");
    }
```

CC @TimeConqueror

**Comment by mitchej123** [comment] 2021-05-16 17:14
Fixed on the next release.

**Closed** 2021-05-16 17:14 UTC

**Comment by hron84** [comment] 2021-06-26 06:43
I experienced this with a customized Regrowth pack, set to the English language. @mitchej123 do you plan to release the fix anytime in the near future? Your work is amazing and could help a lot in progression in my Regrowth world.
