### ISSUE TITLE
crash with automagy

### ISSUE THREAD

**Issue by Pa4ok** [GTNewHorizons/NotEnoughItems#272] opened 2022-08-19 13:44 UTC
crash on showing block cosmetic solid recipe

![image](https://user-images.githubusercontent.com/40999563/185631669-105072b3-e162-4b51-a000-e4c8390512ca.png)

stacktrace 
https://hastebin.com/ahupamaxez.css

**Comment by miozune** [comment] 2022-08-20 03:26
Duplicate of https://github.com/GTNewHorizons/NotEnoughItems/issues/266. But now I think we can just try-catch the method

**Closed** 2022-08-20 09:41 UTC
