### ISSUE TITLE
Nonfunctional NEI Locking Mode

### ISSUE THREAD

**Issue by RaidhoSketch** [GTNewHorizons/NotEnoughItems#460] opened 2024-02-20 12:41 UTC
Hearkening back to #437, while preventing the change in the settings proper, the cheating mode can still be switched while holding ctrl, even in the cheats-disabled worlds.

**Comment by Caedis** [comment] 2024-02-20 14:20
Closed as duplicate of #437

**Closed by Caedis** 2024-02-20 14:20 UTC
