### ISSUE TITLE
Trying to mouse over ore processing causes massive mouse / highlight displacement.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/NotEnoughItems#550] opened 2024-10-24 23:53 UTC
gtnh 2.7.0 beta 3 with nei .44. Just noticed this was happening, at least in the copper ore processing screen.
Below i'm mousing over a huge part higher than the actual tooltip is expecting me to be mousing over. Basically at the top left corner of the tooltip.
![image](https://github.com/user-attachments/assets/6384ec3b-847a-43e6-afc2-732d6d0487bb)
![image](https://github.com/user-attachments/assets/8bc7b8d6-9695-46ee-b363-742ad8964796)

**Comment by Alexdoru** [comment] 2024-10-24 23:55
duplicate of many other tickets, update NEi custom diagram : https://github.com/GTNewHorizons/nei-custom-diagram/releases

**Closed by Alexdoru** 2024-10-24 23:55 UTC

**Comment by Alexdoru** [comment] 2024-10-24 23:56
Furthermore you should make all issues on the [main repo](https://github.com/GTNewHorizons/NewHorizons/issues) and not on particular mods because as we can see here you completely failed and made the ticket on the wrong repo. The bug isn't within NEI but within another mod
