### ISSUE TITLE
[Bug] ExNihilo + NEI

### ISSUE THREAD

**Issue by BazZziliuS** [GTNewHorizons/NotEnoughItems#265] opened 2022-07-09 14:31 UTC
In the Ex Nihilo fashion, when viewing the chances of falling out in different resolutions, there is no chance.
If you change the setting to "Auto resolution" then the percentage of items falling out is shown.

![image](https://user-images.githubusercontent.com/18011884/178110157-534640af-3497-4ccd-85e0-e158689de91f.png)

![image](https://user-images.githubusercontent.com/18011884/178110161-9d85e704-9eed-408f-8146-e28a455b75f0.png)

NotEnoughItems-1.7.10-2.2.12-GTNH-4-g91e9b2a.dirty
CodeChickenLib-1.7.10-1.1.5.3-1-gc84c687
OptiFine Version: OptiFine_1.7.10_HD_U_E7
ExNihilo-1.38-53
Forge{10.13.4.1614}

**Comment by miozune** [comment] 2022-07-09 14:43
Duplicate of #242

**Closed by miozune** 2022-07-09 14:43 UTC
